#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Text-Markdown
Version  : 1.000031
Release  : 10
URL      : https://cpan.metacpan.org/authors/id/B/BO/BOBTFISH/Text-Markdown-1.000031.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/B/BO/BOBTFISH/Text-Markdown-1.000031.tar.gz
Summary  : 'Convert Markdown syntax to (X)HTML'
Group    : Development/Tools
License  : BSD-3-Clause
Requires: perl-Text-Markdown-bin = %{version}-%{release}
Requires: perl-Text-Markdown-license = %{version}-%{release}
Requires: perl-Text-Markdown-man = %{version}-%{release}
Requires: perl-Text-Markdown-perl = %{version}-%{release}
BuildRequires : buildreq-cpan
BuildRequires : perl(Algorithm::Diff)
BuildRequires : perl(Exporter::Tiny)
BuildRequires : perl(List::MoreUtils)
BuildRequires : perl(Module::Install)
BuildRequires : perl(Sub::Uplevel)
BuildRequires : perl(Test::Differences)
BuildRequires : perl(Test::Exception)
BuildRequires : perl(Text::Diff)

%description
NAME
Text::Markdown - Convert Markdown syntax to (X)HTML
SYNOPSIS
use Text::Markdown 'markdown';
my $html = markdown($text);

%package bin
Summary: bin components for the perl-Text-Markdown package.
Group: Binaries
Requires: perl-Text-Markdown-license = %{version}-%{release}

%description bin
bin components for the perl-Text-Markdown package.


%package dev
Summary: dev components for the perl-Text-Markdown package.
Group: Development
Requires: perl-Text-Markdown-bin = %{version}-%{release}
Provides: perl-Text-Markdown-devel = %{version}-%{release}
Requires: perl-Text-Markdown = %{version}-%{release}

%description dev
dev components for the perl-Text-Markdown package.


%package license
Summary: license components for the perl-Text-Markdown package.
Group: Default

%description license
license components for the perl-Text-Markdown package.


%package man
Summary: man components for the perl-Text-Markdown package.
Group: Default

%description man
man components for the perl-Text-Markdown package.


%package perl
Summary: perl components for the perl-Text-Markdown package.
Group: Default
Requires: perl-Text-Markdown = %{version}-%{release}

%description perl
perl components for the perl-Text-Markdown package.


%prep
%setup -q -n Text-Markdown-1.000031
cd %{_builddir}/Text-Markdown-1.000031

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-Text-Markdown
cp %{_builddir}/Text-Markdown-1.000031/License.text %{buildroot}/usr/share/package-licenses/perl-Text-Markdown/cfbdb59a10e2b5b650837ed03373b40cfce44171
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/Markdown.pl

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Text::Markdown.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-Text-Markdown/cfbdb59a10e2b5b650837ed03373b40cfce44171

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/Markdown.pl.1

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/vendor_perl/5.32.1/Text/Markdown.pm
