#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Text-Markdown
Version  : 1.000031
Release  : 3
URL      : https://cpan.metacpan.org/authors/id/B/BO/BOBTFISH/Text-Markdown-1.000031.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/B/BO/BOBTFISH/Text-Markdown-1.000031.tar.gz
Summary  : 'Convert Markdown syntax to (X)HTML'
Group    : Development/Tools
License  : BSD-3-Clause
Requires: perl-Text-Markdown-bin
Requires: perl-Text-Markdown-man
BuildRequires : buildreq-cpan
BuildRequires : perl(List::MoreUtils)
BuildRequires : perl(Module::Install)
BuildRequires : perl(Sub::Uplevel)
BuildRequires : perl(Test::Differences)
BuildRequires : perl(Test::Exception)
BuildRequires : perl(Text::Diff)

%description
NAME
Text::Markdown - Convert Markdown syntax to (X)HTML
SYNOPSIS
use Text::Markdown 'markdown';
my $html = markdown($text);

%package bin
Summary: bin components for the perl-Text-Markdown package.
Group: Binaries
Requires: perl-Text-Markdown-man

%description bin
bin components for the perl-Text-Markdown package.


%package dev
Summary: dev components for the perl-Text-Markdown package.
Group: Development
Requires: perl-Text-Markdown-bin
Provides: perl-Text-Markdown-devel

%description dev
dev components for the perl-Text-Markdown package.


%package doc
Summary: doc components for the perl-Text-Markdown package.
Group: Documentation
Requires: perl-Text-Markdown-man

%description doc
doc components for the perl-Text-Markdown package.


%package man
Summary: man components for the perl-Text-Markdown package.
Group: Default

%description man
man components for the perl-Text-Markdown package.


%prep
%setup -q -n Text-Markdown-1.000031

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/perl-Text-Markdown
cp License.text %{buildroot}/usr/share/doc/perl-Text-Markdown/License.text
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/Text/Markdown.pm

%files bin
%defattr(-,root,root,-)
/usr/bin/Markdown.pl

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Text::Markdown.3

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/perl\-Text\-Markdown/*

%files man
%defattr(-,root,root,-)
/usr/share/man/man1/Markdown.pl.1
